moringaawwards/urls.py
from django.contrib import admin
from django.urls import include
from django.conf.urls import url

urlpatterns = [
    url('admin/', admin.site.urls),
    url('',include('postAndRate.urls')),
]

postAndRate/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    url('^register/',views.register,name="register"),
    url('^profile/',views.profile,name="profile"),
    url('^login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    url('^logout',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    url('^api/projects/$', views.ProjectList.as_view(),name="all_projects_api"),
    url('^api/profiles/$',views.ProfileList.as_view(),name="all_profiles_api"),
    url('^ajax/rate/(?P<pk>\d+)',views.AjaxRating,name="ajaxrating"),
    url(r'^$',views.Index_view,name="index_view"),
    url(r'^upload/$',views.Upload_Project,name="upload_project"),
    url(r'^rating/(?P<pk>\d+)$',views.RateProject,name="rate_project"),
    url(r'^myprofile/',views.User_Profile,name="my_profile"),
    url(r'^endpoints/',views.Endpoints,name="endpoints")
]

postAndRate/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

class Project(models.Model):
    
    title = models.CharField(max_length=40)
    description = models.TextField()
    link = models.CharField(max_length=255)
    image = CloudinaryField('postedPhotos')
    user = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username} {self.title} Project'

class Rating(models.Model):

    design = models.IntegerField(choices=[(i,i) for i in range(1,11)])
    usability = models.IntegerField(choices=[(i,i) for i in range(1,11)])
    content = models.IntegerField(choices=[(i,i) for i in range(1,11)])
    project = models.ForeignKey(Project,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE) 

    def __str__(self):
        return f'{self.user.username} {self.project.title} Rating'

class Profile(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)
    profilePicture = CloudinaryField('profilePicture')
    bio = models.TextField(blank=True)

    def __str__(self):
        return f'{self.user.username} Profile'

postAndRate/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Project,Rating, Profile

class UserRegisterForm(UserCreationForm):

    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username','email','password1','password2']

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username','email']

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['bio','profilePicture']

class ProjectUploadForm(forms.ModelForm):
 
    class Meta:
        model = Project
        fields = ["title","description","link","image"]

class RatingUploadForm(forms.ModelForm):

    class Meta:
        model = Rating
        fields = ["design","usability","content"]

postAndRate/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm,ProfileUpdateForm,UserUpdateForm,ProjectUploadForm,RatingUploadForm
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from .models import Project,Rating,Profile
from django.db.models import Avg
from rest_framework.response import Response
from rest_framework.views import APIView
from .serializer import ProfileSerializer,ProjectSerializer
from django.contrib.auth.models import User
from django.http import JsonResponse

def Index_view(request):
    '''
    This is the function based view for the homepage
    '''
    title = "home"
    projects = Project.objects.all().order_by('-pk')
    context = {
        "title":title,
        "projects":projects,
    }
    
    return render(request,"projects/index.html",context)

@login_required
def Upload_Project(request):
    '''
    This is the function based view for uploading a project to the site
    '''
    current_user = request.user
    if request.method == "POST":
        form = ProjectUploadForm(request.POST,request.FILES)
        if form.is_valid():
            project = form.save(commit=False)
            project.user = current_user
            project.save()
            return redirect(Index_view)
    else:
        form = ProjectUploadForm()
    context = {
        "form":form
    }

    return render(request,"projects/createproject.html",context)

@login_required
def RateProject(request,pk):
    '''
    Function to display single Project and rate it
    '''
    project = Project.objects.get(id=pk)
    title = "Rating"
    current_user = request.user
    project_rating = Rating.objects.filter(project=project).order_by("pk")
    current_user_id = request.user.id
    project_rated = Rating.objects.filter(user=current_user_id)


    design_mean_rating = []
    for d_rating in project_rating:
        design_mean_rating.append(d_rating.design)
    try:
        design_average = sum(design_mean_rating)/len(design_mean_rating)
        design_percent = design_average * 10
    except ZeroDivisionError:
        design_average = "0"
        design_percent = 0

    usability_mean_rating = []
    for u_rating in project_rating:
        usability_mean_rating.append(u_rating.usability)
    try:
        usability_average = sum(usability_mean_rating)/len(usability_mean_rating)
        usability_percent = usability_average *10
    except ZeroDivisionError:
        usability_average = "0"
        usability_percent = 0
    
    content_mean_rating = []
    for c_rating in project_rating:
        content_mean_rating.append(c_rating.content)
    try:
        content_average = sum(content_mean_rating)/len(content_mean_rating)
        content_percent = content_average * 10
    except ZeroDivisionError:
        content_average = "0"
        content_percent = 0

    
    form = RatingUploadForm()

    context = {
        "project":project,
        "form":form,
        "project_rating":project_rating,
        "design_average":design_average,
        "content_average":content_average,
        "usability_average":usability_average,
        "usability_percent":usability_percent,
        "content_percent":content_percent,
        "design_percent":design_percent
    }

    return render(request,"projects/rate.html",context)

@login_required
def AjaxRating(request,pk):
    '''
    Ajax function for uploading user rating
    '''

    project = Project.objects.get(id=pk)
    current_user_id = request.user.id
    current_user = request.user.username
    project_rated = Rating.objects.filter(user=current_user_id)

    if request.method == "POST":
        if project_rated == None:
            design = request.POST.get("design")
            usability = request.POST.get("usability")
            content = request.POST.get("content")
            rating = Rating(design=design,usability=usability,content=content,project=project,user=request.user)
            rating.save()
            data2={"design":design,"usability":usability,"content":content,"uid":current_user_id,"user":current_user,"success":"Successfuly rated"}
            data = {'success': 'You have successfuly rated this project'}
            return JsonResponse(data2)
        else:
            project_rated.delete()
            design = request.POST.get("design")
            usability = request.POST.get("usability")
            content = request.POST.get("content")
            rating = Rating(design=design,usability=usability,content=content,project=project,user=request.user)
            rating.save()
            data2={"design":design,"usability":usability,"content":content,"uid":current_user_id,"success":"Successfuly updated the rating to this project"}
            data = {'success': 'You have successfuly rated this project'}
            return JsonResponse(data2)

@login_required
def User_Profile(request):
    current_user = request.user
    context = {
        "current_user":current_user
    }
    return render(request,"projects/profileDetails.html",context)

@login_required
def Endpoints(request):
    title = "Endpoints"
    context = {
        "title":title
    }
    return render(request,"projects/endpoints.html",context)
    
class ProjectList(APIView):
    def get(self,request,format=None):
        all_projects = Project.objects.all()
        serializers = ProjectSerializer(all_projects,many=True)
        return Response(serializers.data)

class ProfileList(APIView):
    def get(self,request,format=None):
        all_profiles = Profile.objects.all()
        serializers = ProfileSerializer(all_profiles,many=True)
        return Response(serializers.data)

def register(request):
    '''
    This method will allow registration of users by rendering the template to display the registration form
    '''
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f"Your Account Has Been Successfully Created .Please Login!")
            return redirect('login')
    else:
        form = UserRegisterForm()
    context = {
        'form':form
    }
    return render(request,"users/register.html",context)

@login_required
def profile(request):
    '''
    This method handles the user profile 
    '''
    title = 'Profile'
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST,instance=request.user)
        p_form = ProfileUpdateForm(request.POST,request.FILES,instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request,f"You Have Successfully Updated Your Profile!")
            return redirect('profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)
    context = {
        'title':title,
        'u_form':u_form,
        'p_form':p_form 
    }
    return render(request,'users/profile.html',context)

postAndRate/templates/projects/base.html
{% load bootstrap4 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    {% block styles %}
        {% bootstrap_css %}
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        <link href="https://fonts.googleapis.com/css?family=Trochut&display=swap" rel="stylesheet">
    {% endblock %}

    {% if title %}
    <title>Moringaawaards - {{ title }}</title>
    {% else %}
    <title>Moringaawaards</title>
    {% endif %}

</head>
<body>
    
    {% include 'projects/navbar.html' %}

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    
    {% block content %}

    {% endblock %}

    {% block scripts %}
        {% bootstrap_javascript jquery='full' %}
        <script src="{% static 'js/jquery.easypiechart.js' %}"></script>
        <script src="{% static 'js/scripts.js' %}"></script>
    {% endblock %}
</body>
</html>

postAndRate/templates/projects/createproject.html
{% extends 'projects/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
<div class="row">
<div class="col-md-3">
    <h1 class="upload-form-heading">How To Upload</h1>
    <ol>
        <li>Title:Your project Name</li>
        <li>Description:A description about your project you can also include technologys used here</li>
        <li>Link: Full link to your site /li>
        <li>Image:Upload screenshot of the homepage</li>
    </ol>
</div>
<div class="col-md-6">
<h1 class="upload-form-heading">Upload Project</h1>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    
    <div class="form-group">
        <button class="btn btn-outline-info" type="submit">Upload Image</button>
    </div>
</form>
</div>

<div class="col-md-3"></div>
</div>
</div>
{% endblock %}

postAndRate/templates/projects/endpoints.html
{% extends 'projects/base.html' %}

{% block content %}
<div class="container">
    <div class="jumbotron">
        <h1>Endpoints</h1>
    </div>
    <h1>Use Our Apis</h1>
    <ol>
        <li>
            <p>All projects endpoint:
            <a href="{% url 'all_projects_api' %}">click here</a>
            </p>
            <p>This api will query the database for all projects submitted by users</p>
        </li>
        <li>
            <p>All profiles endpoint:
            <a href="{% url 'all_profiles_api' %}">click here</a>
            </p> 
            <p>This api will query the database for all peoples profile</p>
        </li>
    </ol>
</div>
{% endblock %}

postAndRate/templates/projects/index.html
{% extends 'projects/base.html' %}

{% block content %}
<div class="landing-page">
    <h1 class="landing-page-heading text-center">Moringaawaards</h1>
</div>
<div class="bg-projects">
<div class="container" >
<div class="row project-row">
    {% if projects %}

        {% for project in projects %}
        
        <div class="col-md-4">
        <div class="card" style="width: 18rem;">
            <img src="{{ project.image.url }}" class="card-img-top" alt="Project image">
            <div class="card-body">
                <div class="project-owner-display">
                    <img src="{{project.user.profile.profilePicture.url}}" alt="profile picture" class="rounded-circle custom-display border border-warning">
                    <p class="ml-2">Uploaded by: {{ project.user.username }}</p>
                </div>
                <p class="card-text">Project Name: {{ project.title }}</p>
            </div>
            <div class="card-footer">
                <a href="{% url 'rate_project' project.id %}"><button id="button-rate">View & Rate This Site</button></a>
            </div>
          </div>
        </div>
        {% endfor %}

    {% endif %}
</div>
</div>
</div>
{% endblock %}

postAndRate/templates/projects/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <a class="navbar-brand" href="/"><svg width="141" height="22.3" viewBox="0 0 280 44.3">
        <path class="logo-fill" id="logo-a1" d="M1.2,20.8c1-5.1,5.5-8.7,11.9-8.7c7.4,0,13.1,3.1,13.1,13.1v18.6h-6.3l-0.8-4c-2.2,2.7-5.1,4.5-9.6,4.5 C4.2,44.3,0,41,0,34.8s5.5-10.2,13.3-10.2h5.2v-1.4c0-3.5-2.6-4.6-5.5-4.6c-2.2,0-4.4,0.7-5.4,3.6L1.2,20.8z M11.3,37.8 c3.5,0,7.2-2.4,7.2-6.4v-0.6h-5.1c-3.3-0.1-5.3,1.2-5.3,3.9C8.1,36.2,9.2,37.8,11.3,37.8z"></path>
        <path class="logo-fill" id="logo-a2" d="M151,20.8c1-5.1,5.5-8.7,11.9-8.7c7.4,0,13.1,3.1,13.1,13.1v18.6h-6.3l-0.8-4c-2.2,2.7-5.1,4.5-9.6,4.5 c-5.3,0-9.5-3.3-9.5-9.5s5.5-10.2,13.3-10.2h5.2v-1.4c0-3.5-2.6-4.6-5.5-4.6c-2.2,0-4.4,0.7-5.4,3.6L151,20.8z M161.1,37.8 c3.5,0,7.2-2.4,7.2-6.4v-0.6h-5.1c-3.3,0-5.3,1.2-5.3,4C157.9,36.2,159,37.8,161.1,37.8z"></path>
        <path class="logo-fill" id="logo-r" d="M183,43.9V12.6h7.7v5.1c2.2-3.7,5.7-5.6,9.2-5.6c1.4,0,2.5,0.2,3.8,0.6l-1.4,7.1c-0.9-0.6-1.9-0.9-3.2-0.9 c-4.5,0-8.4,3.7-8.4,13.8v11.1L183,43.9L183,43.9z"></path>
        <path class="logo-fill" id="logo-d" d="M220.1,12.1c3.2,0,6.2,1.6,7.6,3.3V0h7.7v43.9h-7.7v-3.2c-0.9,1.6-3.7,3.7-7.6,3.7c-9.4,0-14.2-6.5-14.2-16.1 S210.7,12.1,220.1,12.1z M221.2,37.8c4,0,7.2-3.3,7.2-9.5s-3.2-9.5-7.2-9.5s-7.2,3.3-7.2,9.5S217.2,37.8,221.2,37.8z"></path>
        <path class="logo-fill" id="logo-s" d="M263.2,17.1l-4.6,4.2c-1.4-1.9-3.5-2.7-5.2-2.7c-1.5,0-2.9,0.9-2.9,2.6c0,1.4,1.1,2.4,3,3 c4.3,1.6,11.3,2.9,11.3,9.6c0,5.7-4.3,10.4-11.1,10.4c-6.5,0-10.9-4.6-12.4-8.4l6.1-3.3c1.1,3,3.2,5.2,6.3,5.2 c2.4,0,3.9-1.1,3.9-3.4c0-2.6-4-3.2-7.8-4.8c-3.4-1.4-6.3-3.6-6.3-8.4s3.9-9.1,10-9.1C257.6,12,261.3,14.1,263.2,17.1z"></path>
        <polygon class="logo-fill" id="logo-w2" points="103,12.6 97.5,34.1 92.2,12.6 85,12.6 79.8,34.1 75.4,21.6 74.9,23.1 72.4,31.1 76.4,43.9 83.2,43.9  88.6,23.7 94,43.9 100.8,43.9 110.8,12.6"></polygon>
        <polygon class="logo-fill" id="logo-w3" points="140.2,12.6 134.6,34.1 129.3,12.6 122.1,12.6 116.9,34.1 112.5,21.6 112,23.1 109.5,31.1 113.5,43.9  120.3,43.9 125.7,23.7 131.1,43.9 137.9,43.9 147.9,12.6"></polygon>
        <path class="logo-fill" id="logo-w1" d="M73.7,12.6l-10,31.2h-6.8l-5.4-20.2l-5.4,20.3h-6.8l-10-31.2h7.8l5.6,21.4L48,12.7h7.1l5.3,21.4L66,12.7 L73.7,12.6L73.7,12.6z"></path>
        <path class="logo-fill" id="logo-p" d="M274.8,33.8c3,0,5.2,2.2,5.2,5.2s-2.2,5.2-5.2,5.2s-5.2-2.2-5.2-5.2S271.9,33.8,274.8,33.8z"></path>
    </svg></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    {% if user.is_authenticated %}
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home <span class="sr-only"></span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#"></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#"></a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Menu
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{% url 'upload_project' %}">Upload Project</a>
            <a class="dropdown-item" href="{% url 'my_profile' %}">Profile</a>
            <a class="dropdown-item" href="{% url 'endpoints' %}">Endpoints</a>
            <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
              </div>
          </div>
          {% else %}
          <ul class="navbar-nav">
          <li class="nav-item">
              <a class="nav-link" href="{% url 'register' %}">Sign Up</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'login' %}" class="nav-link">Sign In</a>
            </li>
          </ul>
            {% endif %}
        </li>
      </ul>
    </div>
  </nav>

postAndRate/templates/projects/profileDetails.html
{% extends 'projects/base.html' %}

{% block content %}

    <div class="container-fluid">
        <div class="media">   
            <img src="{{ current_user.profile.profilePicture.url }}" alt="profile image" class="rounded-circle prof">
            <div class="media-body">
                <h2 class="account-heading ml-4">Username: {{ user.username }}</h2>
                <p class="text-secondary ml-4"> Email: {{ user.email }}</p>
                <p class="text-secondary ml-4">Bio: {{ user.profile.bio }}</p>
            </div>
            <a href="{% url 'profile' %}" class="btn btn-outline-info">Edit Profile</a>
        </div>
        <hr>
        <h2 class="text-center my-profile-heading">My Projects</h2>
        <div class="row">
            {% for project in current_user.project_set.all %}
                <div class="col-md-4">
                    <div class="card" style="width: 18rem;">
                        <img src="{{ project.image.url }}" class="card-img-top" alt="Project image">
                        <div class="card-body">
                            <div class="project-owner-display">
                                <img src="{{ project.user.profile.profilePicture.url }}" alt="profile picture" class="rounded-circle custom-display border border-warning">
                                <p class="ml-2">Uploaded by: {{ project.user.username }}</p>
                            </div>
                            <p class="card-text">Project Name: {{ project.title }}</p>
                        </div>
                        <div class="card-footer">
                            <a href="{% url 'rate_project' project.id %}"><button id="button-rate">View & Rate This Site</button></a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

postAndRate/templates/projects/rate.html
{% extends 'projects/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="rating-page above"
    style="background-image: url({{image.url}});height: 100vh;background-attachment: fixed;">
    <div id="overlay">
        <div class="container-fluid">
            <div class="container spinners">
                <div class="row">
                    <div class="col-md-4">
                        <div class="box">
                            <div class="chart" data-percent="{{content_percent}}">Content {{ content_average }}</div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="box">
                            <div class="chart" data-percent="{{ usability_percent }}">Usability {{ usability_average }}
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="box">
                            <div class="chart" data-percent="{{ design_percent }}">Design {{ design_average }}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>
<div class="container-fluid">
    <h1 class="project-details-heading">Project Details</h1>
    <hr>
    <h2 class="project-details-heading">Project Title</h2>
    <p>{{ project.title }} {{ design_mean }}</p><br>

    <h2 class="project-details-heading">Project Details</h2>
    <p>{{ project.description }}</p><br>

    <h2 class="project-details-heading">Visit The Site</h2>
    <a href="{{project.link}}">Visit Site</a><br>

    <h2 class="project-details-heading">Rate this site</h2>
    <div class="row">
        <!-- <div class="col-md-4"></div> -->
        <div class="col-md-4">
            <h2 class="project-details-heading">Rate</h2>
            <hr>
            <form action="" method="POST" enctype="multipart/form-data" id="ratingform">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="hidden" value="{{ project.id }}" id="project_id">
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Submit Rating</button>
                </div>
            </form>
        </div>
        <div class="col-md-8">
            <h2 class="project-details-heading">Ratings</h2>
            <hr>
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">User</th>
                        <th scope="col">Design</th>
                        <th scope="col">Usability</th>
                        <th scope="col">Content</th>
                    </tr>
                </thead>
                <tbody class="t-data">
                    <tr>
                        <th scope="row">Average</th>
                        <td>All</td>
                        <td>{{ design_average }}</td>
                        <td>{{ usability_average }}</td>
                        <td>{{ content_average }}</td>
                    </tr>
                    {% if project_rating %}
                    {% for rating in project_rating %}
                    <tr class="rate{{rating.user.id}}">
                        <th scope="row">{{ forloop.counter }}</th>
                        <td class="t-user"><img src="{{ rating.user.profilePicture.url }}" alt="profile picture"
                                class="rounded-circle custom-display border border-danger">{{ rating.user.username }}
                        </td>
                        <td class="t-design">{{ rating.design }}</td>
                        <td class="t-usability">{{ rating.usability }}</td>
                        <td class="t-content">{{ rating.content }}</td>
                    </tr>
                    {% endfor %}
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}